# Generated by Django 5.2.7 on 2025-11-02 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('category', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('height_m', models.FloatField(blank=True, null=True)),
                ('mass_kg', models.FloatField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=30, null=True)),
                ('birth_year_bby_aby', models.CharField(blank=True, max_length=20, null=True)),
                ('death_year_bby_aby', models.CharField(blank=True, max_length=20, null=True)),
                ('eye_color', models.CharField(blank=True, max_length=30, null=True)),
                ('hair_color', models.CharField(blank=True, max_length=30, null=True)),
                ('skin_color', models.CharField(blank=True, max_length=30, null=True)),
                ('cybernetics', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('wiki_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('media_type', models.CharField(choices=[('film', 'Film'), ('series', 'Series')], default='film', max_length=10)),
                ('episode', models.IntegerField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('chronology_order', models.IntegerField(blank=True, null=True)),
                ('canonical', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['media_type', 'episode', 'release_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('climate', models.CharField(blank=True, max_length=120, null=True)),
                ('terrain', models.CharField(blank=True, max_length=120, null=True)),
                ('population', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('classification', models.CharField(blank=True, max_length=80, null=True)),
                ('designation', models.CharField(blank=True, max_length=80, null=True)),
                ('language', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_order', models.IntegerField(blank=True, null=True)),
                ('role_name', models.CharField(blank=True, max_length=120, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.character')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.media')),
            ],
            options={
                'unique_together': {('character', 'media')},
            },
        ),
        migrations.CreateModel(
            name='CharacterAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since_year_bby_aby', models.CharField(blank=True, max_length=20, null=True)),
                ('until_year_bby_aby', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.affiliation')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.character')),
            ],
            options={
                'unique_together': {('character', 'affiliation')},
            },
        ),
        migrations.AddField(
            model_name='character',
            name='affiliations',
            field=models.ManyToManyField(blank=True, related_name='members', through='core.CharacterAffiliation', to='core.affiliation'),
        ),
        migrations.AddField(
            model_name='character',
            name='films_and_series',
            field=models.ManyToManyField(blank=True, related_name='cast', through='core.Appearance', to='core.media'),
        ),
        migrations.AddField(
            model_name='character',
            name='homeworld',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.planet'),
        ),
        migrations.AddField(
            model_name='character',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.species'),
        ),
    ]
