# Generated by Django 5.2.7 on 2025-11-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='director',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='opening_crawl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='producer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
