# Generated by Django 5.2.7 on 2025-11-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_media_director_media_opening_crawl_media_producer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='seasons',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
