# Generated by Django 5.2.7 on 2025-11-03 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_media_seasons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='seasons',
        ),
    ]
