# Generated by Django 5.2.7 on 2025-11-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_media_seasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='characters',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='planets',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='species',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='starships',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='vehicles',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
