# Generated by Django 5.2.7 on 2025-11-25 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_region_planet_capital_city_planet_grid_coordinates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanetInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('affiliation', models.CharField(blank=True, max_length=120, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('planet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='core.planet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
